version: '3'
services: 
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: wizard_backend_1
    command: sh -c "./run.sh"
    restart: always
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - db:
          condition: service_healthy
volumes:
  data: